- .travis.yml
- docs/README.md
- docs/deployment-guide.md
- docs/generate-target-hosts.md
On travis we have pinned ansible version to 2.9.16, on the control machine we use 2.9.13 and on the ec2 instances created for local install testing we use 2.9.18.
As per ansible [documentation](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-rhel-centos-or-fedora) 2.10 is not available in yum repositories.
Updated and pinned ansible version across the travis build to 2.9.18
> OPSEXP-846: Update ansible

- scripts/generate-zip.sh
The generated README.txt file now points to docs.alfresco.com pages.
The text:
```
You can find full documentation on how to use the playbook for Enterprise deployments here https://docs.alfresco.com/content-services/latest/install/ansible and for Community deployments here https://docs.alfresco.com/content-services/community/install/ansible
```
> OPSEXP-849: Update generated README.txt to point to official docs rather than GitHub

- .ansible-lint
- .gitignore
- .pre-commit-config.yaml
- .secrets.baseline
- docs/components-upgrade.md
- playbooks/acs.yml
- requirements.txt
- roles/common/defaults/main.yml
- roles/common/tasks/check_upgrades.yml
- roles/common/tasks/main.yml
- roles/repository/molecule/default/converge.yml
- roles/repository/tasks/main.yml
- roles/repository/templates/alfresco.xml
- roles/repository/templates/share.xml
Allow Ansible playbook to proceed to "in-place" upgrades for hotfixes
Previous tasks were using "lineinfile" module which can be tricky to use for formats like xml and idempotency.
Replaced by templates
Ref. OPSEXP-1131
> OPSEXP-1131 ACS hotfix upgrade

- molecule/default/molecule.yml
- roles/activemq/molecule/default/molecule.yml
- roles/adw/molecule/default/molecule.yml
- roles/common/molecule/default/molecule.yml
- roles/java/molecule/default/molecule.yml
- roles/nginx/molecule/default/molecule.yml
- roles/repository/molecule/default/molecule.yml
- roles/search/molecule/default/molecule.yml
- roles/sfs/molecule/default/molecule.yml
- roles/sync/molecule/default/molecule.yml
- roles/tomcat/molecule/default/molecule.yml
- roles/transformers/molecule/default/molecule.yml
- roles/trouter/molecule/default/molecule.yml
OPSEXP-1057
Centos:8 has been removed from mirrors since today, needs to stick back to centos:7
> OPSEXP-1057 Revert to centos:7 for molecule roles tests

- .github/dependabot.yml
avoid spamming travis with many concurrent builds
> [minor] dependabot: limit concurrent PRs to 2

- .travis.yml
OPSEXP-1264
skip_cleanup is quite mandatory when uploading S3 artifacts (all the [examples](https://docs.travis-ci.com/user/deployment/s3/) include it)
> OPSEXP-1264 Fix S3 artifact upload

- molecule/default/create.yml
> OPSEXP-1198 Make sure that root ebs is deleted upon termination for EC2 tests

- roles/repository/tasks/main.yml
OPSEXP-1319
reintroduce privilege escalation for async download job checks that got removed in https://github.com/Alfresco/alfresco-ansible-deployment/pull/243
> OPSEXP-1319 Fix random failure on async download repository task

- 6.2.N-extra-vars.yml
- 7.0.N-extra-vars.yml
- docs/README.md
- group_vars/all.yml
- roles/repository/tasks/main.yml
> Bump tomcat to 9.0.59 due to CVE-2022-23181

- requirements.txt
```
ERROR: Cannot install -r requirements.txt (line 7) and jmespath==1.0.0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested jmespath==1.0.0
boto3 1.21.19 depends on jmespath<1.0.0 and >=0.7.1
```
> Fix for jmespath conflict with boto3

- scripts/generate-comp-ver-table.py
Add explicit sorting to glob to avoid column reordering.
Started to fail on #288
> [minor] Explicit order in versions table of README

- playbooks/acs.yml
ensure external_groups precedence
> OPSEXP-1362: ensure external_groups precedence

- .github/workflows/enteprise.yml
- molecule/default/cleanup.yml
- molecule/multimachine/cleanup.yml
OPSEXP-1328
not sure if there is a way to just skip the cleanup phase that make sense only when running molecule locally (not on CI where the local environment is going to be discarded immediately after)
> OPSEXP-1328 Retry failing destroy during ec2 tests

- molecule/default/side_effects.yml
- playbooks/platform-restart.yml
- roles/java/tasks/main.yml
- roles/tomcat/tasks/main.yml
- tests/molecule_it/script.sh
Adds tests to existing scenarios
fixes #330
Ref. OPSEXP-1424
> OPSEXP-1424: fix setenv.sh being wiped by subsequent roles' plays

- roles/trouter/templates/alfresco-transform-router.service
In case application user is different than Alfresco, T-Router service is not able to start. 
This fix uses the application user defined in `roles/common/vars/main.yml`
Fix #371
> Fixing alfresco user for T-Router service

- community-extra-vars.yml
- group_vars/all.yml
- tests/test-config-community.json
- tests/test-config.json
- tests/test-extra-vars.yml
OPSEXP-1629
generated via https://github.com/Alfresco/alfresco-ansible-deployment/pull/387
> OPSEXP-1629 Bump versions for ACS 7.2.1

- roles/repository/tasks/main.yml
- roles/search/molecule/default/tests/test_search.py
- roles/search/templates/solr.sh.j2
- tests/molecule/secrets.yml
> OPSEXP-1699 Fix compatibility issue with Ansible 2.13

- playbooks/acs.yml
- playbooks/check-versions.yml
- playbooks/platform-cleanup.yml
- playbooks/platform-restart.yml
- playbooks/platform-uninstall.yml
- playbooks/prerequisite_checks.yml
Made another draft with commits to platform playbooks
> OPSEXP-1372 switch to FQN (part 3 - platform-* playbooks)

- .github/workflows/enteprise.yml
- playbooks/acs.yml
- roles/repository/defaults/main.yml
- roles/repository/templates/alfresco-content-monitored-startup.service.j2
- roles/sync/handlers/main.yml
- roles/sync/tasks/main.yml
* Disable fail fast so flaky things won't make all the remaining job canceled 
* Start docker IT after completing docker role tests to lower the overall build time (docker IT and EC2 IT are run in parallel)
OPSEXP-1762
> OPSEXP-1762 Fix flaky elasticsearch integration tests

- .pre-commit-config.yaml
- .secrets.baseline
- group_vars/all.yml
- molecule/default/create.yml
- roles/activemq/molecule/default/tests/test_activemq.py
- roles/adw/tasks/main.yml
- roles/repository/tasks/main.yml
- roles/repository/templates/custom-slingshot-application-context.xml
- roles/search/tasks/main.yml
- roles/search/templates/solrcore.properties.j2
- roles/search_enterprise/tasks/main.yml
- roles/sfs/tasks/main.yml
- roles/sync/tasks/main.yml
- roles/transformers/tasks/main.yml
- roles/trouter/tasks/main.yml
- tests/molecule/secrets.yml
- tests/molecule_it/script.sh
* update detect-secrets to latest version
* remove all pragma to allow secrets AND add them to baseline as not secrets
What I've understood is:
* every time a secret detection get triggered by pre-commit hook:
* `detect-secrets scan --baseline .secrets.baseline` to add new detections to the baseline
* `detect-secrets audit .secrets.baseline` to mark that detection as non-secret
OPSEXP-1742
> OPSEXP-1742 Bump detect-secrets plugin

- roles/search_enterprise/molecule/default/converge.yml
- roles/search_enterprise/molecule/default/verify.yml
- roles/search_enterprise/templates/elasticsearch-connector.service.j2
Ref: OPSEXP-1813
Mostly for consistency/corner-cases as Ansible deploys aio  transformer
> OPSEXP-1813: fix wrong routing for alf-ES media cache url

- .github/actions/pipenv/action.yml
it break very bad with the yesterday release
https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/3337677442/jobs/5524326683
> pin pipenv to 2022.10.12

- .ansible-lint
- .github/workflows/enteprise.yml
- .pre-commit-config.yaml
- docs/deployment-guide.md
- molecule/elasticsearch/molecule.yml
- molecule/elasticsearch/verify.yml
- molecule/multimachine/prepare.yml
- playbooks/acs.yml
- playbooks/prerequisite-checks.yml
- playbooks/search-enterprise-reindex.yml
- roles/common/defaults/main.yml
- roles/repository/templates/alfresco-global.properties.j2
- roles/search_enterprise/defaults/main.yml
- roles/search_enterprise/molecule/default/host_vars/search-ent-instance.yml
- roles/search_enterprise/molecule/default/verify.yml
- roles/search_enterprise/tasks/main.yml
- roles/search_enterprise/templates/elasticsearch-cfg.j2
- roles/search_enterprise/templates/elasticsearch-connector-reindex.service.j2
- roles/search_enterprise/templates/elasticsearch-connector.service.j2
- roles/sync/templates/config.yml.j2
- roles/transformers/handlers/main.yml
- roles/transformers/templates/ats-ate-aio.sh.j2
- roles/trouter/templates/ats-atr.sh.j2
> OPSEXP-1803 Add Search Enteprise reindex service

- docs/developer-guide.md
- scripts/updatecli/updatecli_acs72.yml
- scripts/updatecli/updatecli_acs73.yml
- scripts/updatecli/updatecli_config.yml
https://www.updatecli.io/docs/prologue/introduction/
OPSEXP-1620
update group_vars/all.yml versions with:
```
updatecli apply --config scripts/updatecli/updatecli_config.yml --values scripts/updatecli/updatecli_acs73.yml
```
- support the versions specified in molecule tests
> OPSEXP-1620 Update ACS versions via updatecli

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
- molecule/default/vars-centos7.yml
- roles/activemq/molecule/default/molecule.yml
- roles/adw/molecule/default/molecule.yml
- roles/common/molecule/default/molecule.yml
- roles/java/molecule/default/molecule.yml
- roles/nginx/molecule/default/molecule.yml
- roles/postgres/molecule/default/molecule.yml
- roles/repository/molecule/default/molecule.yml
- roles/search/molecule/default/molecule.yml
- roles/sfs/molecule/default/molecule.yml
- roles/sync/molecule/default/molecule.yml
- roles/tomcat/molecule/default/molecule.yml
- roles/transformers/molecule/default/molecule.yml
- roles/trouter/molecule/default/molecule.yml
Get rid of unreliable centos:7 docker tests
OPSEXP-1891
> OPSEXP-1891 Switch tests to rockylinux 8

- docs/deployment-guide.md
> Fix missing pipenv run in ansible-vault docs

- tests/molecule_it/script.sh
Don’t remember why we skipped idempotence checks for Ansible ec2 integration tests but it should not be really a problem to enable them now.
AC:
The idempotence scenario should be added after converge and before side-effects scenario in [integration test script](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/tests/molecule_it/script.sh#L27)
EC2 integrations tests should be green
> OPSEXP-1741 Enable idempotence checks on EC2 integration tests

- group_vars/all.yml
- playbooks/acs.yml
**Description:**
Task with name "- name: Compare host OS with supported matrix" is currently being skipped most of the time. This is because "skip_os_test" is undefined and because "ansible_distribution_version | int not in os_versions" is failing as well. The transformation to "INT" means that only the major version is kept (E.g.: RedHat 8.6 >> 8). Since "8" is never present in "os_versions" (which contains 8.2, 8.5, 8.6, etc.), then this check is always skipped. According to the documentation, it is supposed to be the opposite, meaning that it's always executed, except if "-i skip_os_test=true" is added as extra var.
Also, the correct ansible distribution for RedHat is "RedHat" and not "RHEL". This causes the "supported_os" to not find anything in case the target OS is RedHat, c.f. …
> Fix OS test check and update supported OSes configuration

- roles/common/tasks/main.yml
- roles/common/vars/CentOS7.yml
- roles/common/vars/Debian.yml
- roles/common/vars/RedHat.yml
- roles/common/vars/RedHat7.yml
- roles/common/vars/RedHat8.yml
- roles/nginx/tasks/main.yml
**Description:**
When using the ansible playbook on a `RHEL 8.6` OS, it fails on the `nginx` part. After investigation, it's because nginx cannot startup due to `SELinux` denying it to write the logs under `{{ logs_folder }}`.
Error:
```
TASK [../roles/nginx : Add required proxy config] ****************************************************************************************************************************************************************************
ok: [aws_testing/mop-alf-ce-nginx]
Friday 31 March 2023  15:55:11 +0000 (0:00:02.097)       0:00:37.473 **********
[started TASK: ../roles/nginx : Remove legacy vhosts.conf file. on aws_testing/mop-alf-ce-nginx]
TASK [../roles/nginx : Remove legacy vhosts.conf file.] *********************************************************************** …
```
> Allow nginx to write logs with SELinux

- .github/workflows/enteprise.yml
- molecule/multimachine/prepare.yml
- molecule/opensearch/cleanup.yml
- molecule/opensearch/converge.yml
- molecule/opensearch/host_vars/search3.yml
- molecule/opensearch/hosts.yml
- molecule/opensearch/molecule.yml
- molecule/opensearch/prepare.yml
- molecule/opensearch/templates/hosts.yml.j2
- molecule/opensearch/vars.yml
- roles/activemq/molecule/default/tests/test_activemq.py
- roles/activemq/tasks/main.yml
- roles/repository/templates/alfresco-global.properties.j2
- scripts/generate-secret.sh
- tests/test-config-latest-nosync.json
> OPSEXP-1779 Add EC2 OpenSearch integration test

- roles/nginx/handlers/main.yml
- roles/nginx/tasks/main.yml
```
CRITICAL Idempotence test failed because of the following tasks:
*  => ../roles/nginx : Apply new SELinux file context to /var/log/alfresco
```
https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/4618606446/jobs/8166474695?pr=572#step:10:2852
> Fixup selinux idempotency

- group_vars/all.yml
- roles/transformers/templates/application.properties.j2
Ref: OPSEXP-1955
Actually not used by the Community transformation architecture but in preparation of OPSEXP-1954 & OPSEXP-1953
> OSPEXP-1955: add client mTLS config

- .github/workflows/enteprise.yml
- 7.0.N-extra-vars.yml
- 7.1.N-extra-vars.yml
- 7.2.N-extra-vars.yml
- 7.3.N-extra-vars.yml
- group_vars/all.yml
- molecule/default/cleanup.yml
- molecule/default/vars-ubuntu20-73.yml
- molecule/default/vars-ubuntu20.yml
- molecule/default/verify.yml
- scripts/updatecli/updatecli_acs73.yml
- scripts/updatecli/updatecli_config.tpl
- tests/test-config-7.3.json
- tests/test-config-latest-nosync.json
- tests/test-config.json
> OPSEXP-2110 Add 7.3.N-extra-vars.yml

- community-extra-vars.yml
- tests/test-config-7.2.json
- tests/test-config-community.json
Ref: OPSEXP-2110
didn't use updatecli because we don't support it and not trivial to do (had to skip targets which are not present in community version)
> OPSEXP-2110 Bump community extra-vars for ACS 7.4.0

- .github/workflows/enteprise.yml
- molecule/opensearch/cleanup.yml
- molecule/opensearch/prepare.yml
with the current max length limitation, opensearch resource on aws during IT get created as:
```
molecule-opensearch-opsexp-N
```
leaving just one digit to avoid collisions
> Make opensearch suite create shorter resource name

- .github/workflows/enteprise.yml
- .github/workflows/plantuml.yml
As per https://github.com/stefanzweifel/git-auto-commit-action#use-in-forks-from-public-repositories
I tried directly on https://github.com/Alfresco/alfresco-ansible-deployment/pull/607 but it doesn't trigger when using `pull_request_target` and I suspect we need this merged on default branch before it get triggered
Ref: OPSEXP-2155
> OPSEXP-2155 Make plantuml workflow autocommit configured as per docs

- docs/SECURITY.md
- docs/deployment-guide.md
- docs/playbook-upgrade.md
- docs/shared-contentstore.md
- group_vars/repository.yml
- inventory_ha.yml
- inventory_ssh.yml
- playbooks/acs.yml
- roles/repository/defaults/main.yml
- roles/repository/meta/argument_specs.yml
- roles/repository/molecule/default/converge.yml
- roles/repository/molecule/default/host_vars/repository-instance.yml
- roles/repository/molecule/default/molecule.yml
- roles/repository/molecule/default/tests/test_repository.py
- roles/repository/tasks/main.yml
- roles/repository/templates/alfresco-global.properties.j2
- roles/sync/molecule/default/converge.yml
Ref: OPSEXP-1280
2 ideas behind this refactoring: 
* Using a "master" template to generate properties computed/computable from the architecture/playbook on one side and another one to add properties from user provided files . Finally use `assemble`  to generate the final config file
* Moving as many properties as possible to a yaml datastructure in the repository group so that we can:
* simplify the properties template to just render key/values
* move some inventory dependent variables outside of the repository role
> OPSEXP-1280: refactor acs repo properties file generation

- roles/java/tasks/keystores.yml
When executing the v2.3.0 onward of the playbook, I always faced an issue where the playbook would hang forever on the `Export certificate chain` task.
When debugging the issue, all variables were properly populated and available in the task, but the `openssl` shell command would never complete:
```bash
[rocky@mop-alf-ce-tool ~]$ ps uxf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
rocky      32241  0.0  0.1 163852  5704 ?        S    15:44   0:00 sshd: rocky@pts/1
rocky      32242  0.0  0.1 233920  3940 pts/1    Ss   15:44   0:00  \_ -bash
rocky      32273  0.0  0.1 268548  4048 pts/1    R+   15:44   0:00      \_ ps uxf
rocky      17174  0.0  0.1 164272  6636 ?        S    15:16   0:01 sshd: rocky@pts/0
rocky      31797  0.0  0.0 222856  3212 pts/0    Ss+ …
```
> Switch openssl stdin to standard password option

- roles/activemq/templates/activemq.service.j2
- roles/search/templates/alfresco-search.service
- roles/search_enterprise/templates/elasticsearch-connector-reindex.service.j2
- roles/search_enterprise/templates/elasticsearch-connector.service.j2
- roles/sfs/templates/alfresco-shared-fs.service
- roles/sync/templates/alfresco-sync.service
- roles/tomcat/templates/alfresco-content.service
- roles/transformers/templates/alfresco-tengine-aio.service
- roles/trouter/templates/alfresco-transform-router.service
As a best practice, the 4 standard paths mentioned [in the doc](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/docs/deployment-guide.md#folder-structure) will most probably be using a dedicated mount/filesystem.
At installation, it is fine since the filesystems should already be mounted (if some needs to be used). However, in case of OS restart, the different services are currently configured to be executed `After=syslog.socket network.target`. With this configuration of the service, it can happen that the OS tries to start the Alfresco components before the filesystem is even available. In such cases, it would obviously fail (`status=203/EXEC`) and therefore not startup the component at all. Example of logs showing that the filesystem for /opt/alfresco/ is mounted …
> Wait for mounts before starting components + add auto-restart on failure

- requirements.yml
- roles/search_enterprise/templates/elasticsearch-connector-reindex.service.j2
> OPSEXP-2176 Allow repo_db_url to override search enterprise reindex configuration

- .github/workflows/enteprise.yml
- .secrets.baseline
- group_vars/all.yml
- group_vars/repository.yml
- molecule/elasticsearch/molecule.yml
- molecule/identity/converge.yml
- molecule/identity/host_vars/identity-instance.yml
- molecule/identity/molecule.yml
- molecule/identity/verify.yml
- molecule/local/molecule.yml
- playbooks/acs.yml
- roles/common/defaults/main.yml
- roles/identity/defaults/main.yml
- roles/identity/meta/argument_specs.yml
- roles/identity/tasks/main.yml
- roles/identity/tasks/realm.yml
- roles/nginx/templates/alfresco_proxy.j2
- roles/repository/defaults/main.yml
- roles/repository/meta/argument_specs.yml
- roles/repository/tasks/main.yml
> OPSEXP-2304 Configure SSO in repository

- playbooks/secrets.yml
Was not taking in account the non-external group, caused by copy-pasting the activemq task which initially doesn't had credentials support (but now has).
Ref: OPSEXP-2304
> OPSEXP-2304 Fixup secret presence for activemq, elasticsearch and identity

- roles/search/tasks/replication.yml
Ref: OPSEXP-2331
```
TASK [../roles/search : Wait for core creation to complete] ********************
ok: [test-gionn-repo2]
ok: [test-gionn-repo1]
TASK [../roles/search : Make sure host do not assume a previous role] **********
ok: [test-gionn-repo2] => (item=alfresco)
ok: [test-gionn-repo1] => (item=alfresco)
ok: [test-gionn-repo2] => (item=archive)
failed: [test-gionn-repo1] (item=archive) => {"ansible_loop_var": "item", "changed": false, "item": "archive", "msg": "The target XML source '/etc/opt/alfresco/search-services/solrhome/archive/conf/solrconfig.xml' does not exist."}
```
> OPSEXP-2331 Fix flaky failure in search role

- roles/nginx/defaults/main.yml
- roles/nginx/meta/argument_specs.yml
- roles/nginx/templates/alfresco_proxy.include.j2
- roles/nginx/templates/alfresco_redirect.conf.j2
> OPSEXP-2354 Fix nginx redirect when behind ELB via argument

- roles/nginx/templates/alfresco_proxy.include.j2
Alfresco Control Center is installed even for Community but it is only accessible from localhost:8881 because of Security Filters and other things. So it is necessary to add the proxy from the main 80/443 ports into the server hosting this ADF-based application so that it can be accessed.
For example, if you try to install a simple Community version, with the current template, you will have a /auth/ URL that will fail if there is no Identity (KeyCloak) component and you won't have access to ACC.
I believe it would be better to add conditions for Identity URL (a condition like `identity` group not empty?) and to remove the condition for ACC (this PR or even better, have a condition like `acc` group not empty?).
> Allow access to Control Center for Community

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
* docker_integration waiting for docker in community is just making overall execution time longer
* docker_integration in enterprise can run on dependabot (nexus and github secrets are available)
> Remove not really needed constraints in workflows

- playbooks/pki.yml
As discussed in issue #623 and then PR #635, I'm creating another PR (the 635 was too far behind, too many changes could come into conflict) that is for subfolder creation in the PKI playbook.
This updated version will create the needed subfolders on both the remote server and the Ansible Control Node as needed (and also fixing a few typos). In the end, it's only updating the line 161 to include any possible directory coming from the `inventory_hostname` variable. The `| dirname` takes care of everything so even if there is no `/` in the name, then the /etc/pki folder gets created (if it doesn't exist yet). And if it does contain one, then it will create both the /etc/pki and any subfolder needed.
I also added a task to create the folder on the Control Node around the end of the file, …
> Create pki subfolders for inventory hosts with slash

- roles/repository/tasks/main.yml
- roles/sync/tasks/main.yml
When not using the internal DB but instead using the external one, the JDBC driver is supposed to be provided inside the `configuration_files/db_connector_repo` and/or `configuration_files/db_connector_sync`. However, the roles for the repository and sync are currently using a source value using `inventory_dir`, which doesn't exist apparently. It's the only 2 path using that:
```bash
$ grep -ri '/configuration_files/' playbooks roles | grep -v molecule
playbooks/pki.yml:    actual_pki_dir: "{{ pki_dir | default('../configuration_files/pki') }}"
roles/repository/tasks/main.yml:        src: "{{ inventory_dir }}/configuration_files/db_connector_repo/"
roles/repository/tasks/main.yml:        src: "{{ role_path }}/../../configuration_files/licenses/"
roles/repository/tasks/main.yml: …
```
> Fix source path for JDBC driver on localhost

- README.md
- docs/README.md
- docs/developer-guide.md
- group_vars/all.yml
> OPSEXP-2424: update OS matrix

- requirements.yml
* Docker collection is managed by molecule plugin
* Bump EC2 collection
Ref: OPSEXP-2446
> OPSEXP-2446 Drop docker collection and bump aws collection

- .gitignore
Hello team,
A very small PR to ignore the folder `configuration_files/db_connector_sync/`, as it was done for other configuration folders, to avoid pushing non-expected files.
Cheers,
Morgan
> Update .gitignore for db_connector_sync config files

- 7.0.N-extra-vars.yml
- 7.1.N-extra-vars.yml
- 7.2.N-extra-vars.yml
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- group_vars/all.yml
Ref: OPSEXP-2505
I see [different versions](https://jdbc.postgresql.org/download/#latest-versions) are maintained mainly depending on java version so I bumped all of them
> OPSEXP-2505 Bump postgresql jdbc connector to fix CVE-2024-1597

- .secrets.baseline
- molecule/identity/verify.yml
- playbooks/acs.yml
- playbooks/secrets.yml
- roles/adf_app/defaults/main.yml
- roles/adf_app/meta/argument_specs.yml
- roles/adf_app/molecule/default/verify.yml
- roles/adf_app/tasks/main.yml
> OPSEXP-2551 Fixup redirect url configuration for adw/acc

- .github/workflows/enteprise.yml
Explicit check on nexus secrets availability to decide if run the tests or not (enterprise cannot work without nexus credentials)
> Skip enterprise workflow when nexus secrets are not available

- docs/_config.yml
I noticed only now that the hamburger menu in mobile mode was not working anymore and a js console error was raising up.
Ref: OPSEXP-2603
> OPSEXP-2603 Fix theme javascript inclusion

- 7.1.N-extra-vars.yml
- 7.2.N-extra-vars.yml
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- community-extra-vars.yml
- docs/developer-guide.md
- docs/overview.md
- group_vars/all.yml
- roles/activemq/defaults/main.yml
- scripts/updatecli/updatecli_acs23.yml
- tests/test-config-7.1.json
- tests/test-config-7.2.json
- tests/test-config-7.3.json
- tests/test-config-7.4.json
- tests/test-config.json
Ref: OPSEXP-2627
Tests of Deprecated versions: https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/8733936648
> OPSEXP-2627: bump components for Fornax release

- .github/workflows/docs.yml
https://github.com/Alfresco/jekyll-build-tools/pull/15
> Fix pages validation when adding new pages

- inventory_ha.yml
- inventory_local.yml
- inventory_ssh.yml
- playbooks/prerun-checks.yml
- roles/repository/templates/alfresco-global.properties.j2
> OPSEXP-2747 Avoid configuring repository with search enterprise for community

- 7.2.N-extra-vars.yml
- community-extra-vars.yml
- docs/overview.md
- group_vars/all.yml
- roles/repository/molecule/default/tests/test_repository.py
- scripts/updatecli/updatecli_acs23.yml
- scripts/updatecli/updatecli_community.yml
- tests/test-config-latest-nosync.json
- tests/test-config.json
> OPSEXP-2870 Bump components for Libra release

- group_vars/all.yml
- molecule/docker_enterprise/molecule.yml
- scripts/updatecli/updatecli_acs23.yml
- tests/test-config.json
> OPSEXP-2895 Revert broken sync amp version which impair indexing in search enterprise

- docs/deployment-guide.md
> OPSEXP-2755 Update the docs with new artifact path

- README.md
- docs/SECRETS.md
- docs/_config.yml
- docs/components-upgrade.md
- docs/deployment-guide.md
- docs/overview.md
- roles/search_enterprise/defaults/main.yml
> OPSEXP-2930 Point links to support.hyland.com

- docs/deployment-guide.md
> DOCS-7967 Fix docs reference where known_urls should be set

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
- .secrets.baseline
- 7.2.N-extra-vars.yml
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- group_vars/all.yml
- molecule/default/tasks/detect_ec2_node_hostname.yml
- molecule/default/vars-ubuntu-community.yml
- roles/common/defaults/main.yml
- roles/identity/molecule/default/molecule.yml
- roles/transformers/tasks/imagemagick.yml
- roles/transformers/tasks/main.yml
- roles/transformers/vars/Debian.yml
- roles/transformers/vars/RedHat8.yml
- roles/transformers/vars/RedHat9.yml
- roles/transformers/vars/Rocky8.yml
- roles/transformers/vars/Rocky9.yml
- roles/transformers/vars/Ubuntu.yml
- roles/transformers/vars/Ubuntu18.yml
- roles/transformers/vars/Ubuntu20.yml
- roles/transformers/vars/Ubuntu22.yml
> OPSEXP-2954 Support ubuntu 24.04

- .github/workflows/docker.yml
- .github/workflows/enteprise.yml
- .github/workflows/updatecli.yml
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
requires:
* https://github.com/Alfresco/alfresco-build-tools/pull/876
> OPSEXP-3019 Switch to arm64 GA runners

- roles/identity/defaults/main.yml
- roles/identity/tasks/main.yml
Bump to v25 as per [supported platforms](https://support.hyland.com/r/Alfresco/Alfresco-Content-Services/23.4/Alfresco-Content-Services/Supported-Platforms)
OPSEXP-2923
> OPSEXP-2923 Bump keycloak to v25

- .github/workflows/updatecli.yml
In this way we can roll updatecli upgrades from a single place
OPSEXP-3066
> OPSEXP-3066 Switch to build-tools updatecli action

- .github/dependabot.yml
Still getting the deprecation notice:
> Your workflow is using a version of actions/cache that is scheduled for deprecation, actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a. Please update your workflow to use either v3 or v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
> Enable dependabot for cache-downloads

- .envrc
- .github/workflows/enteprise.yml
- roles/adf_app/templates/default_server.conf.j2
- roles/nginx/defaults/main.yml
- roles/nginx/meta/argument_specs.yml
- roles/nginx/templates/alfresco_proxy.include.j2
Ref: OPSEX-3015
* Removes limitless requests sizes for adf_app (default should be fine)
* Set more secure requests size and duration limits for repo & share
> OPSEXP-3015: set secure, sensible yet usable default for max upload files

- .github/workflows/enteprise.yml
- .secrets.baseline
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- README.md
- docs/playbook-upgrade.md
- group_vars/all.yml
- molecule/default/vars-ubuntu20-73.yml
- molecule/default/vars-ubuntu22-73.yml
- playbooks/acs.yml
- vars/acs23.yml
- vars/acs73.yml
- vars/acs74.yml
> OPSEXP-3058 Move supported_os vars to version specific vars file

- .secrets.baseline
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- docs/deployment-guide.md
- group_vars/all.yml
- playbooks/acs.yml
- playbooks/group_vars/transformers.yml
- playbooks/prerun-upgrade-checks.yml
- roles/transformers/defaults/main.yml
- roles/transformers/meta/argument_specs.yml
- roles/transformers/molecule/default/converge.yml
- roles/transformers/tasks/imagemagick.yml
- roles/transformers/tasks/libreoffice.yml
- roles/transformers/tasks/main.yml
- roles/transformers/templates/alfresco-tengine-aio.service.j2
- roles/transformers/templates/mtls.properties.j2
- roles/transformers/vars/Debian.yml
- roles/transformers/vars/RedHat.yml
- roles/transformers/vars/RedHat8.yml
- roles/transformers/vars/RedHat9.yml
- roles/transformers/vars/Rocky8.yml
- roles/transformers/vars/Rocky9.yml
- vars/acs23.yml
- vars/acs73.yml
- vars/acs74.yml
> OPSEXP-3053 Refactor transformers role to use default vars

- .secrets.baseline
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- group_vars/all.yml
- playbooks/acs.yml
- playbooks/group_vars/all.yml
- playbooks/group_vars/repository.yml
- playbooks/group_vars/syncservice.yml
- roles/repository/defaults/main.yml
- roles/repository/meta/argument_specs.yml
- roles/repository/tasks/main.yml
- roles/sync/defaults/main.yml
- roles/sync/meta/argument_specs.yml
- roles/sync/tasks/main.yml
- vars/acs23.yml
- vars/acs73.yml
- vars/acs74.yml
> OPSEXP-3054: move jdbc driver vars to sync & repo roles

- playbooks/acs.yml
- playbooks/group_vars/elasticsearch.yml
Use var to pass ES (major) version so can be overridden in a version specific way when needed
Ref: OPSEXP-3118
> OPSEXP-3118: move ES version to version vars

- roles/repository/tasks/main.yml
Prevent ansible logging http credentials while using get_url and loop
OPSEXP-3174
> OPSEXP-3174 Prevent http credentials in ansible logs

- .github/updatecli/updatecli_amis_values.yml
The initial config was made using master configs before merging the v25 updates
OPSEXP-3176
> OPSEXP-3176 Fixup ami bumps for latest RH/RL supported versions

- playbooks/dynamic-facts.yml
- playbooks/include-vars.yml
- playbooks/platform-cleanup.yml
It would fails otherwise when having at least one external activemq/elasticsearch/identity
> Fix external hosts usage in playbooks

- Vagrantfile
- docs/deployment-guide.md
- docs/playbook-upgrade.md
- scripts/vagrant_provision.sh
> OPSEXP-3253 Document workaround for pipenv on Ubuntu 24.04 for Python 3.12

- .github/actions/cache-downloads/action.yml
build where failing more often than usual and realized the cache was outdated
OPSEXP-3298
> OPSEXP-3298 Workaround the downloaded artifacts cache invalidation

- .github/workflows/aws-mq-cleanup.yml
- .github/workflows/delete-mq-configs.yml
OPSEXP-3170 
This PR introduces a GitHub Action to automatically clean up AWS MQ configurations that:
- Have the name prefix `molecule-`
- Are older than 30 days based on their creation timestamp
- Are not currently attached to any active brokers
- Schedules to run on 1st of every month
We are using **.LatestRevision.Created** field to check the age and take delete accordingly.
> OPSEXP-3170 Add workflow to cleanup AWS MQ configuration leftovers

- .github/actions/cache-downloads/action.yml
just a guess at fixing https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/16749955596/job/47417431204#step:3:170
it's the only unusual thing we have in this action
> simplify cache key definition in cache-downloads action

- .github/actions/cache-downloads/action.yml
Hopefully fix https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/18284025793
> Hopefully workaround dependabot failure in handling this action
