Alfresco/alfresco-ansible-deployment

- .travis.yml
- tests/test-config-acs6-stack.json
- tests/test-config-community.json
- tests/test-config.json
DTAS_VERSION environment variable has been added to Travis build settings.
Fixed config files to use AMP id rather than name/title.
> OPSEXP-809: Upgrade DTAS usage to v1.0

- docs/deployment-guide.md
Added proxy related quick fixes in the Communication Failures section, see OPSEXP-882
> OPSEXP-882: Added proxy related quick fixes in the Communication Failures section

- roles/transformers/tasks/main.yml
use appropriate ansible variable instead of $releasever
> OPSEXP-886 do not rely on releasever as its behaviour varies

- .secrets.baseline
- .travis.yml
add the 'latest' tag to pushed released (follow version tag)
refs OPSEXP-907
> OPSEXP-907 tag latest

- 6.2.N-extra-vars.yml
- group_vars/all.yml
update openjdk version to 11.0.12 for both ACS 6.2.2 and 7.0
> OPSEXP-969 jdk security

- docs/README.md
> fix broken table [ci skip]

- .pre-commit-config.yaml
- .secrets.baseline
- .travis.yml
- docs/README.md
- requirements.txt
- scripts/generate-comp-ver-table.py
Scenario
Someone made changes in values
Someone want to commit chase
Pre-commit will fail (Readme updated by script) ﻿
Someone need to “git add .” ﻿
Someone commit again(with automated updated Readme file)
Tested, if new file 8.0.N-extra-vars.yml added to repository, will be included into table.
Problems:
developers using this repository need to have installed python3 with pyyaml library.
> Opsexp 651: Automate version update of deployment components in the readme

- roles/transformers/vars/CentOS7.yml
- roles/transformers/vars/CentOS8.yml
- roles/transformers/vars/RedHat7.yml
- roles/transformers/vars/RedHat8.yml
Fix problems with alfresco ImageMagick (aio) tengine.
Ref: OPSEXP-1154
> OPSEXP-1154 fix string split syntax

- .github/workflows/contrib-sync.yml
- .github/workflows/contributions.yml
- .secrets.baseline
- .travis.yml
- CONTRIBUTING.md
External PR acceptance (manual process)
See https://alfresco.atlassian.net/wiki/spaces/TECH/pages/624721946/Accepting+external+contributions
Ref. OPSEXP-1159
> OPSEXP-1159 Add support for external PR

- roles/activemq/tasks/main.yml
- roles/nginx/templates/alfresco.conf
- roles/nginx/templates/alfresco_redirect.conf
- roles/repository/tasks/main.yml
- roles/search/templates/solr.in.sh
- roles/sfs/templates/ats-shared-fs.sh
- roles/sync/templates/syncservice.sh
- roles/tomcat/defaults/main.yml
- roles/tomcat/tasks/main.yml
- roles/tomcat/vars/main.yml
- roles/transformers/templates/ats-ate-aio.sh
- roles/trouter/templates/alfresco-transform-router.service
- roles/trouter/templates/ats-atr.sh
> OPSEXP-1172 fix hardcoded templates

- .travis.yml
> Move ansible version from travis settings to yml config

- .travis.yml
- requirements.txt
- roles/activemq/molecule/default/molecule.yml
- roles/activemq/molecule/default/tests/test_activemq.py
- roles/adw/molecule/default/molecule.yml
- roles/adw/molecule/default/tests/test_adw.py
- roles/common/molecule/default/tests/test_common.py
- roles/java/molecule/default/tests/test_java.py
- roles/nginx/molecule/default/molecule.yml
- roles/nginx/molecule/default/tests/test_nginx.py
- roles/repository/molecule/default/molecule.yml
- roles/repository/molecule/default/tests/test_repository.py
- roles/search/molecule/default/molecule.yml
- roles/search/molecule/default/tests/test_search.py
- roles/sfs/molecule/default/molecule.yml
- roles/sfs/molecule/default/tests/test_sfs.py
- roles/sync/molecule/default/molecule.yml
- roles/sync/molecule/default/tests/test_sync.py
- roles/tomcat/molecule/default/molecule.yml
- roles/tomcat/molecule/default/tests/test_tomcat.py
- roles/transformers/molecule/default/molecule.yml
- roles/transformers/molecule/default/tests/test_transform.py
- roles/trouter/molecule/default/molecule.yml
- roles/trouter/molecule/default/tests/test_trouter.py
> OPSEXP-1054 Upgrade molecule and molecule-docker

- .github/dependabot.yml
> OPSEXP-1054 Enable dependabot for pip dependencies

- .travis.yml
> OPSEXP-1209 Enable building dependabot PR

- .pylintrc
- requirements.txt
https://github.com/Alfresco/alfresco-ansible-deployment/pull/235
https://github.com/Alfresco/alfresco-ansible-deployment/pull/236
https://github.com/Alfresco/alfresco-ansible-deployment/pull/237
> OPSEXP-1209 Bump minor dependencies

- .ansible-lint
- .pre-commit-config.yaml
- .secrets.baseline
- .travis.yml
- molecule/default/create.yml
- molecule/default/prepare.yml
- molecule/default/verify.yml
- roles/search/templates/solrcore.properties
- scripts/generate-comp-ver-table.py
> OPSEXP-1249 Run pre-commit during build

- .travis.yml
- docs/README.md
- molecule/default/create.yml
- molecule/default/destroy.yml
- requirements.txt
- requirements.yml
> OPSEXP-1263 Move to ansible-core 2.12

- .travis.yml
- roles/postgres/handlers/main.yml
- roles/postgres/tasks/main.yml
- roles/repository/handlers/main.yml
- roles/repository/tasks/main.yml
- roles/sync/handlers/main.yml
- roles/sync/tasks/main.yml
- roles/transformers/tasks/main.yml
> OPSEXP-1217 retry molecule test on failure

- .ansible-lint
- docs/deployment-guide.md
- inventory_local.yml
- inventory_nfs.yml
- inventory_ssh.yml
- molecule/manual-activemq/README.md
- molecule/manual-activemq/hosts.yml
- molecule/manual-activemq/molecule.yml
- molecule/manual-activemq/vars.yml
- playbooks/acs.yml
- roles/activemq/molecule/default/molecule.yml
- roles/activemq/tasks/main.yml
- roles/common/defaults/main.yml
- roles/common/tasks/main.yml
- roles/sync/molecule/default/molecule.yml
- roles/sync/templates/config.yml.j2
- roles/transformers/molecule/default/molecule.yml
- roles/trouter/molecule/default/molecule.yml
> OPSEXP-1238 External ActiveMQ

- .github/dependabot.yml
To avoid getting an update every week with little value
> Skip boto3 patch upgrades for dependabot

- roles/transformers/tasks/main.yml
> OPSEXP-1319 Test suggested workaround for unreliable libreoffice download

- .github/workflows/enteprise.yml
- 7.0.N-extra-vars.yml
- 7.1.N-extra-vars.yml
- docs/README.md
- group_vars/all.yml
- molecule/default/vars-rhel7.yml
- molecule/default/vars-rhel8.yml
- molecule/default/vars-ubuntu18.yml
- molecule/default/vars-ubuntu20-community.yml
- roles/common/tasks/secrets.yml
- tests/test-7.1-vars.yml
- tests/test-config-7.0.json
- tests/test-config-7.1.json
- tests/test-config-community.json
Ref: OPSEXP-1350
bump version for release and cleanup
> OPSEXP-1350: bump component versions to 7.2.0 platform release

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
> [minor] Skip molecule tests for documentation PRs

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
> [minor] Ignore docs changes in community pull requests builds too

- docs/SECRETS.md
> OPSEXP-1303 Document secrets present in the playbook

- .github/workflows/community.yml
- group_vars/all.yml
- roles/postgres/molecule/default/converge.yml
- roles/postgres/molecule/default/molecule.yml
- roles/postgres/molecule/default/tests/test_postgres.py
- roles/postgres/tasks/main.yml
> OPSEXP-1373 Use different users for different databases

- roles/adw/defaults/main.yml
- roles/adw/handlers/main.yml
- roles/adw/molecule/default/host_vars/adw-instance.yml
- roles/adw/molecule/default/molecule.yml
- roles/adw/molecule/default/tests/test_adw.py
- roles/adw/tasks/main.yml
- roles/adw/tasks/nginx.yml
- roles/adw/templates/alfresco_adw.conf
- roles/adw/vars/main.yml
OPSEXP-1404: controled usage of become plugin in adw role
> OPSEXP-1404: controled usage of become plugin in adw role

- playbooks/acs.yml
- roles/search/handlers/main.yml
- roles/search/molecule/default/host_vars/search-instance.yml
- roles/search/molecule/default/molecule.yml
- roles/search/molecule/default/tests/test_search.py
- roles/search/tasks/main.yml
OPSEXP-1411 controled usage of become plugin in ansible search role
> OPSEXP-1411 controled usage of become plugin in ansible search role

- playbooks/acs.yml
- roles/adw/defaults/main.yml
- roles/adw/handlers/main.yml
- roles/adw/molecule/default/host_vars/adw-instance.yml
- roles/adw/molecule/default/molecule.yml
- roles/adw/molecule/default/tests/test_adw.py
- roles/adw/tasks/main.yml
- roles/adw/tasks/nginx.yml
- roles/adw/templates/alfresco_adw.conf
- roles/adw/vars/main.yml
- roles/nginx/handlers/main.yml
- roles/nginx/molecule/default/host_vars/nginx-instance.yml
- roles/nginx/molecule/default/molecule.yml
- roles/nginx/molecule/default/tests/test_nginx.py
- roles/nginx/tasks/main.yml
- roles/nginx/tasks/vhosts.yml
- roles/nginx/vars/Ubuntu18.04.yml
- roles/nginx/vars/main.yml
OPSEXP-1406 controled become usage in nginx role
> OPSEXP-1406 controled become usage in nginx role

- playbooks/acs.yml
- roles/common/defaults/main.yml
- roles/sync/defaults/main.yml
- roles/sync/handlers/main.yml
- roles/sync/molecule/default/host_vars/syncservice-instance.yml
- roles/sync/molecule/default/molecule.yml
- roles/sync/molecule/default/tests/test_sync.py
- roles/sync/tasks/main.yml
OPSEXP-1416: controled usage of become plugin in ansible sync role
> OPSEXP-1416: controled usage of become plugin in ansible sync role

- requirements.yml
- roles/repository/defaults/main.yml
- roles/repository/molecule/default/host_vars/repository-instance.yml
- roles/repository/molecule/default/tests/test_repository.py
- roles/repository/tasks/main.yml
- roles/repository/templates/alfresco-global.properties.j2
Set bruteforce params using an easy way to pass properties (reusable by users)
> OPSEXP-1310: bruteforce mitigation

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
- 6.2.N-extra-vars.yml
- 7.0.N-extra-vars.yml
- 7.1.N-extra-vars.yml
- group_vars/all.yml
> OPSEXP-1438 Bump openjdk to 11.0.15

- docs/deployment-guide.md
- roles/postgres/molecule/default/tests/test_postgres.py
- roles/postgres/tasks/main.yml
OPSEXP-1376
* application users are not superusers anymore
* access to default schema is revoked https://dba.stackexchange.com/a/35317/5179
> OPSEXP-1376 Fix postgres users too broad privileges

- playbooks/secrets.yml
- roles/activemq/defaults/main.yml
- roles/activemq/molecule/default/converge.yml
- roles/activemq/molecule/default/tests/test_activemq.py
- roles/activemq/tasks/main.yml
- roles/activemq/templates/activemq.sh.j2
- roles/common/vars/CentOS7.yml
- roles/common/vars/CentOS8.yml
- roles/common/vars/Debian.yml
- roles/common/vars/RedHat7.yml
- roles/common/vars/RedHat8.yml
> OPSEXP-1459: ActiveMQ authentication setup

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
- docs/SECURITY.md
- group_vars/trusted_resource_consumers.yml
- inventory_ha.yml
- inventory_local.yml
- inventory_ssh.yml
Ref: OPSEXP-1307
Add a data structure that can be used to address OPSEXP-1308 and OPSEXP-1309.
> OPSEXP-1307: add basic data structure for CSRF & CORS config

- docs/deployment-guide.md
- playbooks/secrets.yml
- roles/repository/tasks/main.yml
OPSEXP-1305
https://docs.alfresco.com/content-services/latest/admin/security/#alfresco-keystore-configuration
> OPSEXP-1305 Handle custom keystore password

- roles/common/vars/CentOS7.yml
- roles/common/vars/CentOS8.yml
- roles/common/vars/Debian.yml
- roles/common/vars/RedHat7.yml
- roles/common/vars/RedHat8.yml
curl has been added in the common roles vars.
> OPSEXP-1505 Fix curl issue in the env

- group_vars/all.yml
> OPSEXP-1563 Allow overriding maven repository URL

- roles/postgres/molecule/default/tests/test_postgres.py
- roles/repository/molecule/default/tests/test_repository.py
> OPSEXP-1488 Improve tests for upcoming ACS 7.3

- README.md
> Improve the release section in README

- .github/actions/pipenv/action.yml
- .github/workflows/community.yml
- .github/workflows/enteprise.yml
> OPSEXP-1661:  Author new github action on ansible repository to avoid duplications in workflows

- roles/sync/defaults/main.yml
- roles/sync/templates/syncservice.sh.j2
- roles/sync/vars/main.yml
* Disable JMX by default
* Fix random startup error due to port conflicts
OPSEXP-1377
> OPSEXP-1377 Support configuring jmx/rmi in sync service

- roles/common/defaults/main.yml
> Hacktoberfest: deleted not defined port variable

- .github/workflows/mirror-libreoffice.yml
OPSEXP-1696
last manual build: https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/3180841728
> OPSEXP-1696 Add new workflow to mirror libreoffice on nexus

- .github/actions/galaxy/action.yml
> OPSEXP-1755 Better cache handling for ansible galaxy

- roles/transformers/tasks/main.yml
- roles/transformers/vars/main.yml
> OPSEXP-1756 Switch to nexus for libreoffice packages

- .github/actions/galaxy/action.yml
> OPSEXP-1755 Fixup missing roles in galaxy cache handling

- playbooks/check-versions.yml
I had a random failure on the CI and no clues to what happened (and forgot to link it here)
> Add version info in check versions playbook messages

- 6.2.N-extra-vars.yml
- 7.0.N-extra-vars.yml
- 7.1.N-extra-vars.yml
- community-extra-vars.yml
- group_vars/all.yml
- roles/repository/tasks/main.yml
- roles/repository/vars/main.yml
- roles/search/tasks/main.yml
- roles/search_enterprise/tasks/main.yml
- roles/sfs/tasks/main.yml
- roles/transformers/tasks/main.yml
- roles/transformers/templates/ats-ate-aio.sh.j2
- roles/trouter/tasks/main.yml
- roles/trouter/templates/ats-atr.sh.j2
- tests/test-7.1-vars.yml
OPSEXP-1753
Inline comments on the PR for the changes that are not really just refactoring
> OPSEXP-1753 Support variable artifacts name

- molecule/multimachine/cleanup.yml
- playbooks/platform-uninstall.yml
Fixed cleanup.yml and platform-uninstall.yml files
> OPSEXP-1649 Fix uninstall playbook failure at clustered EC2 test

- .github/actions/galaxy/action.yml
> OPSEXP-1772 Bump actions/cache in galaxy action

- .github/workflows/enteprise.yml
- molecule/multimachine/cleanup.yml
- molecule/multimachine/prepare.yml
OPSEXP-1783
requires https://github.com/Alfresco/alfresco-build-tools/pull/150
> OPSEXP-1783 Fix mq broker creation when branch contains non-alphanumeric chars

- docs/deployment-guide.md
- inventory_ha.yml
- inventory_local.yml
- inventory_ssh.yml
- molecule/multimachine/cleanup.yml
- molecule/multimachine/prepare.yml
- playbooks/acs.yml
- playbooks/secrets-init.yml
- playbooks/secrets.yml
- roles/common/defaults/main.yml
- roles/repository/templates/alfresco-global.properties.j2
- roles/search_enterprise/molecule/default/converge.yml
- roles/search_enterprise/molecule/default/molecule.yml
- roles/search_enterprise/tasks/main.yml
- roles/search_enterprise/templates/elasticsearch-connector.service.j2
- tests/molecule/secrets.yml
> OPSEXP-1771 External elasticsearch cluster

- roles/repository/templates/share-config-custom.xml.j2
Workaround for  https://github.com/Alfresco/acs-community-packaging/issues/367
> workaround for user admin in community

- .github/workflows/enteprise.yml
- community-extra-vars.yml
- docs/README.md
- roles/repository/molecule/default/host_vars/repository-instance.yml
- roles/repository/tasks/main.yml
- tests/test-config-community.json
* update version table in docs/README.md
OPSEXP-1795
> OPSEXP-1795 Bump community extra vars for ACS 7.3

- 7.1.N-extra-vars.yml
- tests/test-7.1-vars.yml
> OPSEXP-1829 Support search enterprise for ACS 7.1

- .github/workflows/enteprise.yml
- scripts/generate-zip.sh
> OPSEXP-1795 Fixup release workflow

- .ansible-lint
- .github/workflows/community.yml
- .github/workflows/enteprise.yml
- .github/workflows/precommit.yml
- .pre-commit-config.yaml
- playbooks/platform-cleanup.yml
- playbooks/platform-restart.yml
> OPSEXP-1748 Reuse pipenv ansible-lint in pre-commit

- .github/workflows/enteprise.yml
- community-extra-vars.yml
- group_vars/all.yml
* fixing the actual issue
* fixing the github workflow that was injecting nexus credentials even when not meant to
Fix #521
> OPSEXP-1904 Fix community referencing the enterprise repo

- 7.0.N-extra-vars.yml
- 7.1.N-extra-vars.yml
- 7.2.N-extra-vars.yml
- group_vars/all.yml
> OPSEXP-1832 update imagemagick package 

- docs/deployment-guide.md
> OPSEXP-1936 Move quickstart at the start of deployment guide

- docs/README.md
spotted while @Amy-Hyland was working on DOCS-7045
> Add Search enterprise component to the table

- docs/README.md
> OPSEXP-1846 Add link to ansible version in docs

- .github/workflows/release.yml
- scripts/generate-zip.sh
Ref: OPSEXP-1990
Tested build script in: https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/4556555199/jobs/8037061270
> OPSEXP-1990: refactor zip builder script

- molecule/multimachine/prepare.yml
- molecule/opensearch/prepare.yml
- scripts/generate-secret.sh
Fixup for:
>   TASK [Create mq broker] ********************************************************
>   fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["aws", "mq", "create-broker", "--broker-name", "molecule-opsexp-2066-ags-amps-4616474575", "--deployment-mode", "SINGLE_INSTANCE", "--engine-type", "ACTIVEMQ", "--host-instance-type", "mq.t3.micro", "--engine-version", "5.15.15", "--users", "", "--security-groups", "sg-0c9f3c163ed13570c", "--publicly-accessible", "--no-auto-minor-version-upgrade"], "delta": "0:00:00.973254", "end": "2023-04-05 08:49:54.723013", "msg": "non-zero return code", "rc": 252, "start": "2023-04-05 08:49:53.749759", "stderr": "\nError parsing parameter '--users': Expected: ',', received: '}' for input:\nPassword=xADswRC5#0QgU4zbkRc+}Yg7kfy[rfP9#,Username=alfres …
> OPSEXP-1645 Improve enterprise workflow stability

- .secrets.baseline
- docs/SECURITY.md
- molecule/pki/verify.yml
- playbooks/acs.yml
- roles/repository/templates/alfresco-global.properties.j2
- roles/transformers/templates/ats-ate-aio.sh.j2
- roles/transformers/templates/mtls.properties.j2
- roles/trouter/defaults/main.yml
- roles/trouter/meta/argument_specs.yml
- roles/trouter/tasks/main.yml
- roles/trouter/templates/alfresco-transform-router.service
- roles/trouter/templates/ats-atr.sh.j2
- roles/trouter/templates/mtls.properties.j2
> OPSEXP-1954: add mTLS auth support for the trouter

- Vagrantfile
- docs/deployment-guide.md
> OPSEXP-2086 Bump python compatibility to 3.9

- group_vars/all.yml
- playbooks/acs.yml
skip mtls if versions do not support it
> OPSEXP-2112: add version checks for ATS mTLS  config

- 7.2.N-extra-vars.yml
- scripts/updatecli/updatecli_acs72.yml
> OPSEXP-2110 Bump 7.2.N-extra-vars with updatecli

- README.md
- docs/developer-guide.md
> OPSEXP-2110 Document current release process steps

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
- molecule/elasticsearch/molecule.yml
- molecule/local/molecule.yml
- molecule/pki/molecule.yml
- roles/acc/molecule/default/molecule.yml
- roles/activemq/molecule/default/molecule.yml
- roles/adw/molecule/default/molecule.yml
- roles/common/molecule/default/molecule.yml
- roles/elasticsearch/molecule/default/molecule.yml
- roles/java/molecule/default/molecule.yml
- roles/nginx/molecule/default/molecule.yml
- roles/postgres/molecule/default/molecule.yml
- roles/postgres/molecule/default/tests/test_postgres.py
- roles/repository/molecule/default/molecule.yml
- roles/search/molecule/default/molecule.yml
- roles/search_enterprise/molecule/default/molecule.yml
- roles/sfs/molecule/default/molecule.yml
- roles/sync/molecule/default/molecule.yml
- roles/tomcat/molecule/default/molecule.yml
- roles/transformers/molecule/default/molecule.yml
- roles/trouter/molecule/default/molecule.yml
> OPSEXP-2161: Pin Rocky Linux version to minor

- .github/workflows/community.yml
- .secrets.baseline
- roles/identity/meta/argument_specs.yml
- roles/identity/molecule/default/converge.yml
- roles/identity/tasks/realm.yml
> OPSEXP-2304 Fixup community workflow

- .secrets.baseline
- molecule/identity/molecule.yml
- molecule/identity/verify.yml
- playbooks/acs.yml
- roles/adf_app/tasks/main.yml
> OPSEXP-2305 Enable SSO for adf apps

- molecule/identity/verify.yml
- requirements.yml
- roles/repository/defaults/main.yml
- roles/repository/meta/argument_specs.yml
- roles/repository/tasks/main.yml
- roles/repository/tasks/share.yml
- roles/repository/templates/share-config.properties.j2
- roles/repository/vars/main.yml
> OPSEXP-2314 Enable SSO for Share

- .secrets.baseline
- molecule/default/prepare.yml
- molecule/identity/molecule.yml
- molecule/identity/prepare.yml
- molecule/identity/verify.yml
- playbooks/acs.yml
- roles/identity/tasks/realm.yml
- roles/repository/tasks/share.yml
- roles/repository/templates/share-config-custom.xml.j2
- roles/repository/templates/share-config.properties.j2
- roles/repository/vars/main.yml
* fixup redirect uris in the alfresco realm
* make sure that clients use the main alfresco fqdn to access keycloak
Ref: OPSEXP-2314
> OPSEXP-2314 Make sure that share SSO config is properly setup

- .secrets.baseline
- molecule/identity/verify.yml
- playbooks/acs.yml
- roles/adf_app/defaults/main.yml
- roles/adf_app/molecule/default/verify.yml
- roles/adf_app/tasks/main.yml
- roles/identity/tasks/realm.yml
- roles/nginx/templates/alfresco_proxy_headers.include.j2
> OPSEXP-2335 Fixup sso across adf apps

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
- .pre-commit-config.yaml
- docs/README.md
- docs/SECRETS.md
- docs/deployment-guide.md
> OPSEXP-2328 Document initial SSO support

- .secrets.baseline
- group_vars/all.yml
- playbooks/acs.yml
- roles/adf_app/molecule/default/converge.yml
> OPSEXP-2359: support newer checksum format for ADW 4.1+

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
- 7.2.N-extra-vars.yml
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- community-extra-vars.yml
- docs/README.md
- group_vars/all.yml
- molecule/multimachine/prepare.yml
- roles/activemq/defaults/main.yml
- roles/java/tasks/keystores.yml
- roles/postgres/tasks/apt_repo.yml
- roles/postgres/vars/Ubuntu18.yml
- roles/search_enterprise/molecule/default/verify.yml
- scripts/updatecli/updatecli_acs23.yml
- scripts/updatecli/updatecli_acs72.yml
- scripts/updatecli/updatecli_acs73.yml
- scripts/updatecli/updatecli_acs74.yml
- scripts/updatecli/updatecli_community.yml
- scripts/updatecli/updatecli_config.tpl
- tests/test-config-7.3.json
- tests/test-config-community.json
- tests/test-config-latest-nosync.json
- tests/test-config.json
> OPSEXP-2366: Updatecli bumps to 23.1

- .github/workflows/community.yml
- .github/workflows/docker.yml
- .github/workflows/enteprise.yml
- molecule/pki/molecule.yml
- molecule/pki/verify.yml
> OPSEXP-2399: move pki molecule scenario to comunity workflow

- docs/deployment-guide.md
- inventory_local.yml
- playbooks/prerun-checks.yml
> OPSEXP-2406: remove broken defaults in local inventory and update doc

- .secrets.baseline
- playbooks/acs.yml
> OPSEXP-2409: add when condition in post_tasks for consistency

- .secrets.baseline
- docs/SECURITY.md
- docs/deployment-guide.md
- group_vars/all.yml
- group_vars/repository.yml
- molecule/identity/verify.yml
- playbooks/acs.yml
- requirements.yml
- roles/identity/defaults/main.yml
- roles/identity/meta/argument_specs.yml
- roles/identity/tasks/main.yml
- roles/identity/tasks/realm.yml
- roles/nginx/templates/alfresco_proxy.include.j2
> OPSEXP-2329 Fix keycloak endpoint and console access behind proxy

- .github/workflows/enteprise.yml
- molecule/default/vars-rocky8.yml
- tests/test-config-7.4.json
> OPSEXP-2404 Ensure we are really testing acs 7.4.0 on ec2

- tests/test-config-7.4.json
Ref: OPSEXP-2404
https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/7101414522/job/19329806111#step:10:4070
> OPSEXP-2404 Fixup ec2 acs 7.4 test

- roles/sync/tasks/main.yml
improvement from the dsync integration with alfresco-cloud-infrastructure
> Fix jdbc driver download for sync service

- .pre-commit-config.yaml
- .secrets.baseline
- Pipfile
- Pipfile.lock
- molecule/default/molecule.yml
- molecule/elasticsearch/molecule.yml
- molecule/identity/molecule.yml
- molecule/local/molecule.yml
- molecule/multimachine/molecule.yml
- molecule/opensearch/molecule.yml
- molecule/pki/molecule.yml
- roles/activemq/molecule/default/tests/test_activemq.py
- roles/common/molecule/default/tests/test_common.py
- roles/java/molecule/default/tests/test_java.py
- roles/nginx/molecule/default/tests/test_nginx.py
- roles/postgres/molecule/default/molecule.yml
- roles/repository/molecule/default/molecule.yml
- roles/repository/molecule/default/tests/test_repository.py
- roles/repository/templates/share-config-custom.xml.j2
- roles/search/molecule/default/molecule.yml
- roles/search/molecule/default/tests/test_search.py
- roles/search_enterprise/molecule/default/molecule.yml
- roles/sfs/molecule/default/tests/test_sfs.py
- roles/sync/molecule/default/molecule.yml
- roles/sync/molecule/default/tests/test_sync.py
- roles/tomcat/molecule/default/tests/test_tomcat.py
- roles/transformers/molecule/default/molecule.yml
- roles/transformers/molecule/default/tests/test_transform.py
- roles/trouter/molecule/default/molecule.yml
- roles/trouter/molecule/default/tests/test_trouter.py
* Bump pre-commit hooks
* Pin pre-commit python version to the main playbook python version
Ref: OPSEXP-2156
> OPSEXP-2156 Bump molecule to v6.0.3

- requirements.yml
> OPSEXP-2446 Bump all remaining galaxy dependencies

- 7.2.N-extra-vars.yml
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- README.md
- docs/developer-guide.md
- group_vars/all.yml
* alfresco-search-services to 2.0.9
Ref: OPSEXP-2446
> OPSEXP-2446 Bump components for draco release

- roles/repository/molecule/default/host_vars/repository-instance.yml
- roles/repository/molecule/default/tests/test_repository.py
> OPSEXP-2544: repository role - improve tests

- .github/workflows/updatecli.yml
- 7.2.N-extra-vars.yml
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- community-extra-vars.yml
- docs/README.md
- group_vars/all.yml
- scripts/updatecli/updatecli_acs74.yml
> OPSEXP-2573: bump components with latest security fixes

- docs/README.md
- docs/index.md
> OPSEXP-2603 Reintroduce README to be shown on the github repository page

- .github/workflows/docs.yml
Looks like the version-to-sha script picked up a very old version O.o
Ref: OPSEXP-2603
> OPSEXP-2603 Fixup deployment to GitHub Pages

- playbooks/secrets-init.yml
- playbooks/secrets.yml
- roles/repository/tasks/main.yml
> OPSEXP-2549 Set reposearch_shared_secret when search is defined

- docs/_config.yml
> OPSEXP-2603 Fixup url in jekyll config

- .github/workflows/docs.yml
> OPSEXP-2639 Switch to upstream jekyll workflow

- 7.4.N-extra-vars.yml
- docs/overview.md
- scripts/updatecli/updatecli_acs74.yml
Ref: OPSEXP-2627
As per PRODMAN-7980
> OPSEXP-2627: ATS 4.1.1 is now supported with ACS 7.4

- README.md
- docs/_config.yml
> OPSEXP-2622 Move dev docs to repo readme

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
> OPSEXP-2662 do not trigger molecule workflows when changing docs workflow

- .github/workflows/updatecli.yml
- 7.2.N-extra-vars.yml
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- community-extra-vars.yml
- group_vars/all.yml
- scripts/updatecli/updatecli_acs71.yml
- scripts/updatecli/updatecli_acs73.yml
- tests/test-config-7.2.json
- tests/test-config-7.3.json
- tests/test-config-7.4.json
> OPSEXP-2676 Bump components for Gemini release

- README.md
- docs/overview.md
> OPSEXP-2676 Bump docs for Gemini release

- group_vars/all.yml
> OPSEXP-2691 Add aarch64 support in java role

- .github/workflows/community.yml
- requirements.yml
- roles/identity/defaults/main.yml
- roles/identity/meta/argument_specs.yml
- roles/identity/tasks/main.yml
> OPSEXP-2668 Bump keycloak to 24.0.5

- .github/workflows/docker.yml
- .github/workflows/enteprise.yml
> OPSEXP-2760 Switch to new ARM64 runners

- .github/workflows/enteprise.yml
- 7.2.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- community-extra-vars.yml
- docs/overview.md
- galaxy.yml
- group_vars/all.yml
- roles/activemq/defaults/main.yml
- scripts/updatecli/updatecli_acs23.yml
- scripts/updatecli/updatecli_community.yml
- tests/test-config-community.json
- tests/test-config-latest-nosync.json
- tests/test-config.json
OPSEXP-2777
extended run: https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/10629751439
> OPSEXP-2777 Bump components for Indus release

- roles/common/tasks/check_upgrades.yml
quick workaround - better PR coming later
> OPSEXP-2824 do not check for adw which is a stateless frontend app

- roles/search_enterprise/templates/elasticsearch-cfg.j2
- roles/search_enterprise/templates/elasticsearch-connector-reindex.service.j2
- roles/search_enterprise/vars/main.yml
> OPSEXP-2827: escape % char in systemd unit env vars

- roles/repository/templates/alfresco-content-unit-overrides.j2
- roles/search_enterprise/templates/elasticsearch-cfg.j2
- roles/search_enterprise/templates/elasticsearch-connector-reindex.service.j2
- roles/search_enterprise/vars/main.yml
> OPSEXP-2830: always escape % (also fixes consecutive %)

- .secrets.baseline
- molecule/identity/verify.yml
- playbooks/acs.yml
- roles/identity/defaults/main.yml
- roles/identity/meta/argument_specs.yml
- roles/identity/tasks/realm.yml
Ref: OPSEXP-2674
~Will probably need to wait for GA for proper testing~
> OPSEXP-2674 Disable implicit flow with newer adw

- scripts/generate-secret.sh
> OPSEXP-2832 Explicit failure when unable to generate secrets during secrets-init

- .github/workflows/enteprise.yml
> OPSEXP-2753 Trigger ec2 test when PR label ec2-test is added and on master branch

- .github/workflows/kics.yml
> OPSEXP-2121 Fix permission for sarif report from KICS

- .github/workflows/kics.yml
> OPSEXP-2121 Fix permission on KICS workflow

- 7.1.N-extra-vars.yml
- 7.2.N-extra-vars.yml
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- community-extra-vars.yml
- group_vars/all.yml
- scripts/updatecli/updatecli_acs71.yml
> OPSEXP-2874 Bump Search Services to 2.0.12

- .secrets.baseline
- group_vars/acc.yml
- group_vars/adw.yml
- playbooks/acs.yml
> OPSEXP-2927 ADW/ACC config via group vars

- .github/workflows/release.yml
> OPSEXP-2755 Use alfresco-build-tools/maven-deploy-file action to publish release on nexus

- .github/actions/cache-downloads/action.yml
- .github/actions/molecule_integration_ec2/action.yml
- .github/workflows/community.yml
- .github/workflows/docker.yml
- .github/workflows/enteprise.yml
- .gitignore
- inventory_local.yml
- playbooks/prefetch-artifacts.yml
- roles/activemq/tasks/main.yml
- roles/tomcat/tasks/main.yml
> OPSEXP-2972 Workaround apache mirror flakiness with controller cache

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
* Avoid flaky issues when cache is not created yet
OPSEXP-2972
> OPSEXP-2972 Ensure downloads cache is already available on matrix jobs

- .github/workflows/community.yml
- .github/workflows/enteprise.yml
Fix for https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/12135916286/job/33835930910
OPSEXP-2972
> OPSEXP-2972 Add python actions deps needed by cache-downloads action

- README.md
> OPSEXP-2941 Drop deprecated badge

- roles/repository/tasks/sharedcs.yml
> OPSEXP-2955 Avoid resetting permissions on mounted shared content storage

- .github/actions/setup-workspace/action.yml
- .github/workflows/community.yml
- .github/workflows/enteprise.yml
- .github/workflows/kics.yml
- .github/workflows/updatecli.yml
- group_vars/all.yml
- roles/repository/molecule/default/host_vars/repository-instance.yml
- roles/repository/tasks/sharedcs.yml
- scripts/updatecli/updatecli_acs23.yml
- tests/test-config-aas.json
- tests/test-config-latest-nosync.json
- tests/test-config.json
> OPSEXP-2955 Create next branch for ACS v25

- requirements.yml
> OPSEXP-2954 Bump galaxy deps

- group_vars/all.yml
> OPSEXP-2953 Bump postgres to v16

- scripts/updatecli/updatecli_community.yml
- scripts/updatecli/updatecli_config.tpl
https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/12986314083/job/36212857855
> Fix updatecli pipeline for community

- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- docs/overview.md
- group_vars/all.yml
> OPSEXP-3036 Bump to latest tomcat patch and update README

- .github/workflows/updatecli.yml
https://github.com/Alfresco/alfresco-ansible-deployment/actions/runs/13112289000
> OPSEXP-3036 Do not run updatecli on tags

- roles/repository/templates/share-config-custom.xml.j2
looks like #501 is still not fixed
> fix case issue on showAuthorizationStatus

- community-extra-vars.yml
> OPSEXP-3058 Point community to acs23 vars

- .secrets.baseline
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- group_vars/all.yml
- playbooks/acs.yml
- playbooks/group_vars/search_enterprise.yml
- roles/search_enterprise/defaults/main.yml
- roles/search_enterprise/meta/argument_specs.yml
- roles/search_enterprise/molecule/default/converge.yml
- roles/search_enterprise/molecule/default/verify.yml
- roles/search_enterprise/tasks/main.yml
- roles/search_enterprise/templates/elasticsearch-connector-reindex.service.j2
- roles/search_enterprise/templates/elasticsearch-connector.service.j2
- roles/search_enterprise/vars/main.yml
- vars/acs23.yml
- vars/acs73.yml
- vars/acs74.yml
> OPSEXP-3046 Refactor search_enterprise role to use default vars

- .secrets.baseline
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- group_vars/all.yml
- playbooks/acs.yml
- playbooks/group_vars/syncservice.yml
- playbooks/prerun-upgrade-checks.yml
- roles/sync/defaults/main.yml
- roles/sync/meta/argument_specs.yml
- roles/sync/molecule/default/converge.yml
- roles/sync/molecule/default/molecule.yml
- roles/sync/tasks/configure.yml
- roles/sync/tasks/main.yml
- vars/acs23.yml
- vars/acs73.yml
- vars/acs74.yml
> OPSEXP-3048: add sync download vars as role defaults

- .github/actions/cache-downloads/prefetch-artifacts.yml
- .secrets.baseline
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- group_vars/all.yml
- playbooks/acs.yml
- roles/tomcat/defaults/main.yml
- roles/tomcat/molecule/default/tests/test_tomcat.py
- roles/tomcat/tasks/main.yml
- roles/tomcat/vars/main.yml
- vars/acs23.yml
- vars/acs73.yml
- vars/acs74.yml
> OPSEXP-3051 Refactor tomcat role

- .secrets.baseline
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- group_vars/all.yml
- playbooks/acs.yml
- playbooks/group_vars/transformers.yml
- roles/transformers/defaults/libreoffice.yml
- roles/transformers/defaults/main.yml
- roles/transformers/meta/argument_specs.yml
- roles/transformers/tasks/libreoffice.yml
- roles/transformers/templates/alfresco-tengine-aio.service.j2
- roles/transformers/vars/main.yml
- vars/acs23.yml
- vars/acs73.yml
- vars/acs74.yml
> OPSEXP-3053 Refactor transformers_libreoffice to use default vars

- .secrets.baseline
- 7.3.N-extra-vars.yml
- 7.4.N-extra-vars.yml
- group_vars/all.yml
- playbooks/acs.yml
- playbooks/group_vars/transformers.yml
- roles/transformers/defaults/main.yml
- roles/transformers/meta/argument_specs.yml
- roles/transformers/tasks/imagemagick.yml
- roles/transformers/templates/alfresco-tengine-aio.service.j2
- roles/transformers/vars/Debian.yml
- roles/transformers/vars/RedHat.yml
- roles/transformers/vars/main.yml
- vars/acs23.yml
- vars/acs73.yml
- vars/acs74.yml
> OPSEXP-3053 Refactor transformers_imagemagick to use default vars

- docs/deployment-guide.md
- group_vars/all.yml
- playbooks/acs.yml
- playbooks/group_vars/all.yml
- roles/sync/defaults/main.yml
- roles/sync/meta/argument_specs.yml
- roles/sync/molecule/default/host_vars/syncservice-instance.yml
> OPSEXP-3040 Move sync_db vars from group vars

- .github/actions/setup-workspace/action.yml
- group_vars/all.yml
- playbooks/group_vars/all.yml
> OPSEXP-3040 Move nexus related vars out of group vars

- docs/overview.md
- docs/playbook-upgrade.md
- roles/tomcat/defaults/main.yml
- vars/acs23.yml
- vars/acs25.yml
- vars/acs73.yml
- vars/acs74.yml
> OPSEXP-3153 Prepare release of ansible deployment v3.0.0

- .github/actions/molecule_integration_ec2/action.yml
- .github/workflows/enteprise.yml
> OPSEXP-3146 Use OIDC role to auth to aws  🛂

- roles/repository/tasks/main.yml
- roles/repository/templates/alfresco.xml
Allow overriding properties file for simple jar modules.
OPSEXP-3125
> OPSEXP-3125 Support config folder for jar extensions

- docs/overview.md
- roles/search_enterprise/defaults/main.yml
- roles/sfs/defaults/main.yml
- roles/transformers/defaults/main.yml
- roles/trouter/defaults/main.yml
- vars/acs23.yml
- vars/acs25.yml
- vars/acs73.yml
- vars/acs74.yml
> OPSEXP-3456 Bump versions for Vela release

- requirements.yml
OPSEXP-3456
requires:
* https://github.com/Alfresco/alfresco-ansible-collection/pull/45
> OPSEXP-3456 Bump galaxy dependencies

- roles/nginx/defaults/main.yml
- roles/nginx/molecule/default/verify.yml
OPSEXP-3507
preview for PDF files in adw was broken (infinite loading spinner)
> OPSEXP-3507 Fix worker script CSP directive for webapps
